server:
  host: 127.0.0.1         # 监听的ip地址
  port: 8080              # 监听的端口

jsonwebtoken:
  client:
    secret: "client"      # 密钥
    overdue: 86400                # 过期时间 秒
  admin:
    secret: "admin"      # 密钥
    overdue: 86400                # 过期时间 秒
log:
  writers: file,stdout
  logger_level: INFO
  logger_file: log/api_server.log
  log_format_text: true
  rollingPolicy: size
  log_rotate_date: 1
  log_rotate_size: 1
  log_backup_count: 7